var window=window||this;var cc=cc||{};var jsb=jsb||{};cc.container=null;cc.each=function(obj,iterator,context){if(!obj)return;if(obj instanceof Array)for(var i=0,li=obj.length;i<li;i++){if(iterator.call(context,obj[i],i)===false)return}else for(var key in obj)if(iterator.call(context,obj[key],key)===false)return};
cc.extend=function(target){var sources=arguments.length>=2?Array.prototype.slice.call(arguments,1):[];cc.each(sources,function(src){for(var key in src)if(src.hasOwnProperty(key))target[key]=src[key]});return target};cc.isFunction=function(obj){return typeof obj=="function"};cc.isNumber=function(obj){return typeof obj=="number"||Object.prototype.toString.call(obj)=="[object Number]"};cc.isString=function(obj){return typeof obj=="string"||Object.prototype.toString.call(obj)=="[object String]"};
cc.isArray=function(obj){return Array.isArray(obj)||typeof obj==="object"&&Object.prototype.toString.call(obj)==="[object Array]"};cc.isUndefined=function(obj){return typeof obj==="undefined"};cc.isObject=function(obj){return obj!==null&&typeof obj==="object"};cc.isCrossOrigin=function(url){return false};cc.defineGetterSetter=function(proto,prop,getter,setter){var desc={enumerable:false,configurable:true};getter&&(desc.get=getter);setter&&(desc.set=setter);Object.defineProperty(proto,prop,desc)};
cc.associateWithNative=function(jsobj,superclass_or_instance){};cc.inherits=function(childCtor,parentCtor){function tempCtor(){}tempCtor.prototype=parentCtor.prototype;childCtor.superClass_=parentCtor.prototype;childCtor.prototype=new tempCtor;childCtor.prototype.constructor=childCtor};
cc.base=function(me,opt_methodName,var_args){var caller=arguments.callee.caller;if(caller.superClass_){ret=caller.superClass_.constructor.apply(me,Array.prototype.slice.call(arguments,1));return ret}var args=Array.prototype.slice.call(arguments,2);var foundCaller=false;for(var ctor=me.constructor;ctor;ctor=ctor.superClass_&&ctor.superClass_.constructor)if(ctor.prototype[opt_methodName]===caller)foundCaller=true;else if(foundCaller)return ctor.prototype[opt_methodName].apply(me,args);if(me[opt_methodName]===
caller)return me.constructor.prototype[opt_methodName].apply(me,args);else throw Error("cc.base called from a method of one name "+"to a method of a different name");};var ClassManager={id:0|Math.random()*998,instanceId:0|Math.random()*998,getNewID:function(){return this.id++},getNewInstanceId:function(){return this.instanceId++}};cc.Class=function(){};
cc.Class.extend=function(prop){var _super=this.prototype,prototype,Class,classId,className=prop._className||"",name,desc;initializing=true;prototype=Object.create(_super);initializing=false;fnTest=/xyz/.test(function(){xyz})?/\b_super\b/:/.*/;for(name in prop)prototype[name]=typeof prop[name]=="function"&&typeof _super[name]=="function"&&fnTest.test(prop[name])?function(name,fn){return function(){var tmp=this._super;this._super=_super[name];var ret=fn.apply(this,arguments);this._super=tmp;return ret}}(name,
prop[name]):prop[name];Class=function(){if(!initializing){this.__instanceId=ClassManager.getNewInstanceId();this.ctor&&this.ctor.apply(this,arguments)}};Class.prototype=prototype;Class.prototype.constructor=Class;Class.extend=cc.Class.extend;classId=ClassManager.getNewID();ClassManager[classId]=_super;desc={writable:true,enumerable:false,configurable:true};Class.id=classId;desc.value=classId;Object.defineProperty(prototype,"__pid",desc);return Class};
jsb.registerNativeRef=function(owner,target){if(owner&&target&&owner!==target){var refs=owner.__nativeRefs;if(!refs)refs=owner.__nativeRefs=[];var index=refs.indexOf(target);if(index===-1)owner.__nativeRefs.push(target)}};jsb.unregisterNativeRef=function(owner,target){if(owner&&target&&owner!==target){var refs=owner.__nativeRefs;if(!refs)return;var index=refs.indexOf(target);if(index!==-1)owner.__nativeRefs.splice(index,1)}};
jsb.unregisterAllNativeRefs=function(owner){if(!owner)return;owner.__nativeRefs.length=0};jsb.unregisterChildRefsForNode=function(node,recursive){if(!(node instanceof cc.Node))return;recursive=!!recursive;var children=node.getChildren(),i,l,child;for(i=0,l=children.length;i<l;++i){child=children[i];jsb.unregisterNativeRef(node,child);if(recursive)jsb.unregisterChildRefsForNode(child,recursive)}};
