/**
 * Created by Quyet Nguyen on 6/24/2016.
 */

/* lobby */
socket.LobbyClient.NotConnection = 0;
socket.LobbyClient.Connecting = 1;
socket.LobbyClient.Connected = 2;
socket.LobbyClient.ConnectFailure = 3;
socket.LobbyClient.LostConnection = 4;
socket.LobbyClient.Closed = 5;

socket.LobbyClient.UDT = 0;
socket.LobbyClient.TCP = 1;
socket.LobbyClient.prototype._ctor = function (socketType) {
    this.initClientWithType(socketType);
    return true;
};

/* smartfox */
socket.SmartfoxClient.NotConnection = 0;
socket.SmartfoxClient.Connecting = 1;
socket.SmartfoxClient.Connected = 2;
socket.SmartfoxClient.ConnectFailure = 3;
socket.SmartfoxClient.LostConnection = 4;
socket.SmartfoxClient.Closed = 5;

socket.SmartfoxClient.Handshake = 0;
socket.SmartfoxClient.Login = 1;
socket.SmartfoxClient.Logout = 2;
socket.SmartfoxClient.GetRoomList = 3;
socket.SmartfoxClient.JoinRoom = 4;
socket.SmartfoxClient.AutoJoin = 5;
socket.SmartfoxClient.CreateRoom = 6;
socket.SmartfoxClient.GenericMessage = 7;
socket.SmartfoxClient.ChangeRoomName = 8;
socket.SmartfoxClient.ChangeRoomPassword = 9;
socket.SmartfoxClient.ObjectMessage = 10;
socket.SmartfoxClient.SetRoomVariables = 11;
socket.SmartfoxClient.SetUserVariables = 12;
socket.SmartfoxClient.CallExtension = 13;
socket.SmartfoxClient.LeaveRoom = 14;
socket.SmartfoxClient.SubscribeRoomGroup = 15;
socket.SmartfoxClient.UnsubscribeRoomGroup = 16;
socket.SmartfoxClient.SpectatorToPlayer = 17;
socket.SmartfoxClient.PlayerToSpectator = 18;
socket.SmartfoxClient.ChangeRoomCapacity = 19;
socket.SmartfoxClient.PublicMessage = 20;
socket.SmartfoxClient.PrivateMessage = 21;
socket.SmartfoxClient.ModeratorMessage = 22;
socket.SmartfoxClient.AdminMessage = 23;
socket.SmartfoxClient.KickUser = 24;
socket.SmartfoxClient.BanUser = 25;
socket.SmartfoxClient.ManualDisconnection = 26;
socket.SmartfoxClient.FindRooms = 27;
socket.SmartfoxClient.FindUsers = 28;
socket.SmartfoxClient.PingPong = 29;
socket.SmartfoxClient.SetUserPosition = 30;
//--- Buddy List API Requests -------------------------------------------------
socket.SmartfoxClient.InitBuddyList = 200;
socket.SmartfoxClient.AddBuddy = 201;
socket.SmartfoxClient.BlockBuddy = 202;
socket.SmartfoxClient.RemoveBuddy = 203;
socket.SmartfoxClient.SetBuddyVariables = 204;
socket.SmartfoxClient.GoOnline = 205;
//--- Game API Requests --------------------------------------------------------
socket.SmartfoxClient.InviteUser = 300;
socket.SmartfoxClient.InvitationReply = 301;
socket.SmartfoxClient.CreateSFSGame = 302;
socket.SmartfoxClient.QuickJoinGame = 303;
//only reponse code
socket.SmartfoxClient.UserEnterRoom = 1000,
socket.SmartfoxClient.UserCountChange = 1001;
socket.SmartfoxClient.UserLost  = 1002;
socket.SmartfoxClient.RoomLost = 1003;
socket.SmartfoxClient.UserExitRoom = 1004;
socket.SmartfoxClient.ClientDisconnection = 1005;
socket.SmartfoxClient.ReconnectionFailure = 1006;
socket.SmartfoxClient.SetMMOItemVariables = 1007;

socket.SmartfoxClient.SocketStatus = 3000;


/* electro client*/
socket.ElectroClient.CrossDomainRequest = 1;
socket.ElectroClient.CreateRoomRequest = 2;
socket.ElectroClient.JoinRoomRequest = 3;
socket.ElectroClient.LoginRequest = 4;
socket.ElectroClient.LogOutRequest = 5;
socket.ElectroClient.ValidateAdditionalLoginRequest = 6;
socket.ElectroClient.ValidateAdditionalLoginResponse = 7;
socket.ElectroClient.PublicMessageRequest = 8;
socket.ElectroClient.PrivateMessageRequest = 9;
socket.ElectroClient.LeaveRoomRequest = 10;
socket.ElectroClient.CreateRoomVariableRequest = 11;
socket.ElectroClient.DeleteRoomVariableRequest = 12;
socket.ElectroClient.UpdateRoomVariableRequest = 13;
socket.ElectroClient.GetZonesRequest = 14;
socket.ElectroClient.GetRoomsInZoneRequest = 15;
socket.ElectroClient.UpdateRoomDetailsRequest = 16;
socket.ElectroClient.AddRoomOperatorRequest = 17;
socket.ElectroClient.RemoveRoomOperatorRequest = 18;
socket.ElectroClient.FindZoneAndRoomByNameRequest = 19;
socket.ElectroClient.GetUsersInRoomRequest = 20;
socket.ElectroClient.DeleteUserVariableRequest = 21;
socket.ElectroClient.UpdateUserVariableRequest = 22;
socket.ElectroClient.AddBuddiesRequest = 23;
socket.ElectroClient.RemoveBuddiesRequest = 24;
socket.ElectroClient.EvictUserFromRoomRequest = 25;
socket.ElectroClient.GetUserCountRequest = 26;
socket.ElectroClient.PluginRequest = 27;
socket.ElectroClient.CreateOrJoinGameRequest = 28;
socket.ElectroClient.JoinGameRequest = 29;
socket.ElectroClient.FindGamesRequest = 30;
socket.ElectroClient.GetUserVariablesRequest = 31;
socket.ElectroClient.AggregatePluginRequest = 32;
socket.ElectroClient.GetServerLocalTimeRequest = 33;
socket.ElectroClient.GetGameTypesRequest = 34;
socket.ElectroClient.ConnectionResponse = 35;
socket.ElectroClient.CrossDomainResponse = 36;
socket.ElectroClient.LoginResponse = 37;
socket.ElectroClient.GetZonesResponse = 38;
socket.ElectroClient.GetRoomsInZoneResponse = 39;
socket.ElectroClient.GenericErrorResponse = 40;
socket.ElectroClient.FindZoneAndRoomByNameResponse = 41;
socket.ElectroClient.GetUsersInRoomResponse = 42;
socket.ElectroClient.GetUserCountResponse = 43;
socket.ElectroClient.CreateOrJoinGameResponse = 44;
socket.ElectroClient.FindGamesResponse = 45;
socket.ElectroClient.GetUserVariablesResponse = 46;
socket.ElectroClient.AddBuddiesResponse = 47;
socket.ElectroClient.RemoveBuddiesResponse = 48;
socket.ElectroClient.GetServerLocalTimeResponse = 49;
socket.ElectroClient.GetGameTypesResponse = 50;
socket.ElectroClient.PublicMessageEvent = 51;
socket.ElectroClient.PrivateMessageEvent = 52;
socket.ElectroClient.SessionIdleEvent = 53;
socket.ElectroClient.JoinRoomEvent = 54;
socket.ElectroClient.JoinZoneEvent = 55;
socket.ElectroClient.UserUpdateEvent = 56;
socket.ElectroClient.ZoneUpdateEvent = 57;
socket.ElectroClient.LeaveRoomEvent = 58;
socket.ElectroClient.LeaveZoneEvent = 59;
socket.ElectroClient.RoomVariableUpdateEvent = 60;
socket.ElectroClient.UpdateRoomDetailsEvent = 61;
socket.ElectroClient.BuddyStatusUpdatedEvent = 62;
socket.ElectroClient.UserEvictedFromRoomEvent = 63;
socket.ElectroClient.UserVariableUpdateEvent = 64;
socket.ElectroClient.PluginMessageEvent = 65;
socket.ElectroClient.AggregatePluginMessageEvent = 66;
socket.ElectroClient.RegistryConnectToPreferredGatewayRequest = 67;
socket.ElectroClient.DisconnectedEvent = 68;
socket.ElectroClient.GatewayStartupExceptionsMessage = 69;
socket.ElectroClient.RegistryLoginResponse = 70;
socket.ElectroClient.RegistryConnectionResponse = 71;
socket.ElectroClient.GatewayKickUserRequest = 72;
socket.ElectroClient.ServerKickUserEvent = 73;
socket.ElectroClient.UdpBackchannelEvent = 74;
socket.ElectroClient.Unknown = 75;
socket.ElectroClient.RtmpPlayVideo = 76;
socket.ElectroClient.RtmpEventResponse = 77;
socket.ElectroClient.RtmpRecordVideo = 78;
socket.ElectroClient.RtmpPublishVideo = 79;
socket.ElectroClient.RtmpUnpublishVideo = 80;
socket.ElectroClient.RtmpAppendVideo = 81;
socket.ElectroClient.RtmpStreamingStart = 82;
socket.ElectroClient.RtmpStreamingStop = 83;
socket.ElectroClient.DHInitiate = 84;
socket.ElectroClient.DHPublicNumbers = 85;
socket.ElectroClient.DHSharedModulusRequest = 86;
socket.ElectroClient.DHSharedModulusResponse = 87;
socket.ElectroClient.EncryptionStateChange = 88;
socket.ElectroClient.ConnectionAttemptResponse = 89;
socket.ElectroClient.ConnectionClosedEvent = 90;
socket.ElectroClient.RegisterUDPConnectionRequest = 91;
socket.ElectroClient.RegisterUDPConnectionResponse = 92;
socket.ElectroClient.RemoveUDPConnectionRequest = 93;
socket.ElectroClient.RemoveUDPConnectionResponse = 94;
socket.ElectroClient.PingRequest = 95;
socket.ElectroClient.PingResponse = 96;
socket.ElectroClient.IdleTimeoutWarningEvent = 97;
socket.ElectroClient.MarkGatewayClientLoggedInMessage = 98;